-- Criar o banco de dados
CREATE DATABASE IF NOT EXISTS carteirinhas
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE carteirinhas;

-- CRIAÇÃO DA TABELA ALUNOS
CREATE TABLE IF NOT EXISTS alunos (
id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(150) NOT NULL,
matricula VARCHAR(36) NOT NULL UNIQUE, 
nome_mae VARCHAR(150) DEFAULT NULL, 
data_nascimento DATE NOT NULL,
curso VARCHAR(100) DEFAULT 'ENSINO MEDIO INTEGRAL', 
turma VARCHAR(10) NOT NULL, 
turno VARCHAR(10) NOT NULL,
foto VARCHAR(100), 
ano_letivo YEAR NOT NULL DEFAULT '2026',
impresso TINYINT(1) NOT NULL DEFAULT 0, 
create_at DATETIME NOT NULL DEFAULT NOW()
);

-- CRIAÇÃO DA TABELA TURMAS
CREATE TABLE IF NOT EXISTS turmas (
  id INT AUTO_INCREMENT PRIMARY KEY, 
  sigla VARCHAR(20) NOT NULL UNIQUE, 
  nome VARCHAR(100) NOT NULL);


